-- ============================================================================
-- ESQUEMA DE LA APLICACIÓN DE GESTIÓN INSTITUCIONAL UTNG
-- Todas las instrucciones utilizan IF NOT EXISTS u ON CONFLICT para que este
-- archivo pueda ejecutarse varias veces sin duplicar información.
-- ============================================================================

-- Catálogo de permisos generales asignados a los usuarios.
CREATE TABLE IF NOT EXISTS roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL UNIQUE,
    descripcion VARCHAR(200) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Personas que pueden solicitar préstamos o administrar el sistema.
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id SMALLINT NOT NULL REFERENCES roles(id),
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    correo VARCHAR(160) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    puesto VARCHAR(100),
    departamento VARCHAR(120),
    password_hash VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_acceso TIMESTAMP,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Clasificación utilizada por productos y equipos.
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Existencias prestables; cada registro controla el stock disponible.
CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL REFERENCES categorias(id),
    nombre VARCHAR(140) NOT NULL,
    modelo VARCHAR(100),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    stock_minimo INTEGER NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_producto_nombre_modelo UNIQUE (nombre, modelo)
);

-- Espacios físicos donde se localizan los activos institucionales.
CREATE TABLE IF NOT EXISTS ubicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    edificio VARCHAR(100),
    descripcion VARCHAR(200),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Activos individuales identificados por código y número de serie.
CREATE TABLE IF NOT EXISTS equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL REFERENCES categorias(id),
    ubicacion_id BIGINT REFERENCES ubicaciones(id),
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nombre VARCHAR(140) NOT NULL,
    modelo VARCHAR(100),
    numero_serie VARCHAR(120) UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO'
        CHECK (estado IN ('ACTIVO', 'MANTENIMIENTO', 'BAJA', 'SIN_ASIGNAR')),
    observaciones TEXT,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Encabezado de cada préstamo realizado a un usuario.
CREATE TABLE IF NOT EXISTS prestamos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(40) NOT NULL UNIQUE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    registrado_por BIGINT REFERENCES usuarios(id),
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion_programada DATE NOT NULL,
    fecha_devolucion_real DATE,
    estado VARCHAR(25) NOT NULL DEFAULT 'ACTIVO'
        CHECK (estado IN ('ACTIVO', 'DEVUELTO', 'VENCIDO', 'CANCELADO')),
    motivo VARCHAR(200),
    observaciones TEXT,
    responsiva_aceptada BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Productos y cantidades que pertenecen a cada préstamo.
CREATE TABLE IF NOT EXISTS detalle_prestamo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestamo_id BIGINT NOT NULL REFERENCES prestamos(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES productos(id),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    cantidad_devuelta INTEGER NOT NULL DEFAULT 0 CHECK (cantidad_devuelta >= 0),
    CONSTRAINT uq_detalle_prestamo_producto UNIQUE (prestamo_id, producto_id),
    CONSTRAINT chk_cantidad_devuelta CHECK (cantidad_devuelta <= cantidad)
);

-- Historial de entregas parciales o completas de productos prestados.
CREATE TABLE IF NOT EXISTS devoluciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detalle_prestamo_id BIGINT NOT NULL REFERENCES detalle_prestamo(id),
    recibido_por BIGINT REFERENCES usuarios(id),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT
);

-- Solicitudes de soporte o reparación relacionadas con un equipo.
CREATE TABLE IF NOT EXISTS ordenes_servicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(40) NOT NULL UNIQUE,
    equipo_id BIGINT NOT NULL REFERENCES equipos(id),
    solicitante_id BIGINT NOT NULL REFERENCES usuarios(id),
    responsable_id BIGINT REFERENCES usuarios(id),
    tipo_servicio VARCHAR(80) NOT NULL,
    descripcion TEXT NOT NULL,
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA'
        CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
    estado VARCHAR(25) NOT NULL DEFAULT 'ABIERTA'
        CHECK (estado IN ('ABIERTA', 'EN_PROCESO', 'CERRADA', 'CANCELADA')),
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP
);

-- Trabajos preventivos o correctivos efectuados sobre los equipos.
CREATE TABLE IF NOT EXISTS mantenimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio VARCHAR(40) NOT NULL UNIQUE,
    equipo_id BIGINT NOT NULL REFERENCES equipos(id),
    tecnico_id BIGINT REFERENCES usuarios(id),
    tipo VARCHAR(25) NOT NULL CHECK (tipo IN ('PREVENTIVO', 'CORRECTIVO')),
    fecha_programada DATE NOT NULL,
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    estado VARCHAR(25) NOT NULL DEFAULT 'PROGRAMADO'
        CHECK (estado IN ('PROGRAMADO', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO')),
    prioridad VARCHAR(20) NOT NULL DEFAULT 'MEDIA'
        CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA')),
    diagnostico TEXT,
    trabajo_realizado TEXT,
    costo NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (costo >= 0),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Historial de archivos CSV o ZIP generados desde la pantalla Reportes.
CREATE TABLE IF NOT EXISTS reportes_generados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    ruta VARCHAR(500) NOT NULL,
    creado_por BIGINT REFERENCES usuarios(id),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Metadatos de respaldos; el archivo físico se conserva fuera de PostgreSQL.
CREATE TABLE IF NOT EXISTS respaldos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(180) NOT NULL UNIQUE,
    ruta VARCHAR(500) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('AUTOMATICO', 'MANUAL')),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('EN_PROCESO', 'COMPLETADO', 'FALLIDO')),
    tamano_bytes BIGINT CHECK (tamano_bytes IS NULL OR tamano_bytes >= 0),
    creado_por BIGINT REFERENCES usuarios(id),
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mensaje TEXT
);

-- Índices que aceleran los filtros utilizados por las pantallas.
CREATE INDEX IF NOT EXISTS idx_usuarios_activo ON usuarios(activo);
CREATE INDEX IF NOT EXISTS idx_productos_activo ON productos(activo);
CREATE INDEX IF NOT EXISTS idx_equipos_estado ON equipos(estado);
CREATE INDEX IF NOT EXISTS idx_prestamos_estado ON prestamos(estado);
CREATE INDEX IF NOT EXISTS idx_prestamos_usuario ON prestamos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_ordenes_estado ON ordenes_servicio(estado);
CREATE INDEX IF NOT EXISTS idx_mantenimientos_estado ON mantenimientos(estado);
CREATE INDEX IF NOT EXISTS idx_reportes_fecha ON reportes_generados(creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_respaldos_fecha ON respaldos(creado_en DESC);

-- Roles iniciales requeridos por el sistema.
INSERT INTO roles (nombre, descripcion)
VALUES
    ('ADMINISTRADOR', 'Acceso completo a configuración y catálogos'),
    ('DOCENTE', 'Puede solicitar equipos y consultar sus préstamos'),
    ('TECNICO', 'Atiende órdenes de servicio y mantenimientos'),
    ('ADMINISTRATIVO', 'Consulta y registra operaciones autorizadas')
ON CONFLICT (nombre) DO NOTHING;

-- Categorías mostradas en Inventario y Equipos.
INSERT INTO categorias (nombre, descripcion)
VALUES
    ('Cómputo portátil', 'Laptops y dispositivos transportables'),
    ('Proyección', 'Proyectores y accesorios de presentación'),
    ('Impresión', 'Impresoras y consumibles'),
    ('Monitores', 'Pantallas y monitores'),
    ('Equipo de escritorio', 'Computadoras de escritorio'),
    ('Periféricos', 'Teclados, controles y cables')
ON CONFLICT (nombre) DO NOTHING;

-- Ubicaciones institucionales iniciales.
INSERT INTO ubicaciones (nombre, edificio)
VALUES
    ('Aula 101', 'Edificio A'),
    ('Aula 201', 'Edificio B'),
    ('Administración', 'Edificio Administrativo'),
    ('Taller', 'Edificio de Mantenimiento'),
    ('Laboratorio 2', 'Edificio C'),
    ('Almacén', 'Edificio Administrativo')
ON CONFLICT (nombre) DO NOTHING;

-- Usuario administrador utilizado como perfil inicial de la maqueta.
INSERT INTO usuarios (rol_id, nombre, apellidos, correo, telefono, puesto, departamento)
SELECT r.id, 'Alejandro', 'Herrera Martínez', 'alejandro.herrera@utng.edu.mx',
       '418 000 0000', 'Administrador del sistema', 'Tecnologías de la Información'
FROM roles r
WHERE r.nombre = 'ADMINISTRADOR'
ON CONFLICT (correo) DO NOTHING;

-- Docentes y técnicos disponibles en el formulario de préstamos.
INSERT INTO usuarios (rol_id, nombre, apellidos, correo, puesto, departamento)
SELECT r.id, datos.nombre, datos.apellidos, datos.correo, datos.puesto, datos.departamento
FROM roles r
CROSS JOIN (VALUES
    ('Sofía', 'Castro', 'sofia.castro@utng.edu.mx', 'Docente', 'Tecnologías de la Información'),
    ('Marco', 'Ramírez', 'marco.ramirez@utng.edu.mx', 'Docente', 'Mecatrónica'),
    ('Julia', 'López', 'julia.lopez@utng.edu.mx', 'Docente', 'Procesos Industriales')
) AS datos(nombre, apellidos, correo, puesto, departamento)
WHERE r.nombre = 'DOCENTE'
ON CONFLICT (correo) DO NOTHING;

INSERT INTO usuarios (rol_id, nombre, apellidos, correo, puesto, departamento)
SELECT r.id, 'Luis', 'Pérez', 'luis.perez@utng.edu.mx', 'Técnico', 'Soporte técnico'
FROM roles r
WHERE r.nombre = 'TECNICO'
ON CONFLICT (correo) DO NOTHING;

-- Productos prestables con las existencias observadas en la pantalla original.
INSERT INTO productos (categoria_id, nombre, modelo, stock, stock_minimo)
SELECT c.id, datos.nombre, datos.modelo, datos.stock, datos.stock_minimo
FROM categorias c
JOIN (VALUES
    ('Periféricos', 'Cable HDMI 1.8m', 'HDMI-1.8', 20, 3),
    ('Periféricos', 'Cable HDMI 3m', 'HDMI-3', 8, 2),
    ('Proyección', 'Proyector Epson EB-X51', 'EB-X51', 6, 1),
    ('Proyección', 'Proyector BenQ MH560', 'MH560', 3, 1),
    ('Periféricos', 'Control TV Samsung', 'Samsung universal', 12, 2),
    ('Periféricos', 'Control TV LG', 'LG universal', 7, 2)
) AS datos(categoria, nombre, modelo, stock, stock_minimo)
ON c.nombre = datos.categoria
ON CONFLICT (nombre, modelo) DO NOTHING;

-- Equipos individuales utilizados por órdenes y mantenimientos.
INSERT INTO equipos (categoria_id, ubicacion_id, codigo, nombre, modelo, numero_serie, estado)
SELECT c.id, u.id, datos.codigo, datos.nombre, datos.modelo, datos.serie, datos.estado
FROM (VALUES
    ('Cómputo portátil', 'Aula 101', 'EQ-2026-001', 'Laptop Dell Latitude 3420', 'Latitude 3420', 'CN0M4HRS1', 'ACTIVO'),
    ('Proyección', 'Aula 201', 'EQ-2026-002', 'Proyector Epson EB-X51', 'EB-X51', 'X5N840A35', 'ACTIVO'),
    ('Impresión', 'Administración', 'EQ-2026-003', 'Impresora HP LaserJet 1020', 'LaserJet 1020', 'CN8D13245', 'ACTIVO'),
    ('Monitores', 'Taller', 'EQ-2026-004', 'Monitor LG 24 pulgadas', '24MK400H', '804NT2K12345', 'MANTENIMIENTO'),
    ('Equipo de escritorio', 'Laboratorio 2', 'EQ-2026-005', 'CPU HP ProDesk 400', 'ProDesk 400 G6', '8CG0472KJ5', 'ACTIVO'),
    ('Periféricos', 'Almacén', 'EQ-2026-006', 'Teclado Logitech K120', 'K120', '2310L208A8', 'BAJA')
) AS datos(categoria, ubicacion, codigo, nombre, modelo, serie, estado)
JOIN categorias c ON c.nombre = datos.categoria
JOIN ubicaciones u ON u.nombre = datos.ubicacion
ON CONFLICT (codigo) DO NOTHING;
